language: php
sudo: false
php:
    - 7.0.27
    - 7.1.13
    - 7.2.1
    - "nightly"
matrix:
    fast_finish: true
    allow_failures:
        - php: "nightly"
os:
    - windows
    - linux
before_install:
    - git clone -b stable https://github.com/jedisct1/libsodium.git
    - cd libsodium && sudo ./configure && sudo make check && sudo make install && cd ..
install:
    - pecl install libsodium
    - travis_retry composer install --no-interaction
cache:
    directories:
        - vendor
        - $HOME/.cache/composer
