language: php
sudo: false
php:
    - 7.2.2
#   - 7.3.0
#   - 7.4.0
    - "nightly"
matrix:
    fast_finish: true
    allow_failures:
        - php: "nightly"
os:
    - windows
    - linux
install:
    - travis_retry composer install --no-interaction
cache:
    directories:
        - vendor
        - $HOME/.cache/composer
